# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindowTool(object):
    def setupUi(self, MainWindowTool):
        MainWindowTool.setObjectName(_fromUtf8("MainWindowTool"))
        MainWindowTool.resize(733, 381)
        self.centralwidget = QtGui.QWidget(MainWindowTool)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidgetConfig = QtGui.QTabWidget(self.centralwidget)
        self.tabWidgetConfig.setMinimumSize(QtCore.QSize(220, 0))
        self.tabWidgetConfig.setObjectName(_fromUtf8("tabWidgetConfig"))
        self.ServersTab = QtGui.QWidget()
        self.ServersTab.setObjectName(_fromUtf8("ServersTab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.ServersTab)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setSpacing(1)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tableWidgetServers = QtGui.QTableWidget(self.ServersTab)
        self.tableWidgetServers.setObjectName(_fromUtf8("tableWidgetServers"))
        self.tableWidgetServers.setColumnCount(10)
        self.tableWidgetServers.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetServers.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetServers.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetServers.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetServers.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetServers.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetServers.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetServers.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetServers.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetServers.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetServers.setHorizontalHeaderItem(9, item)
        self.verticalLayout_2.addWidget(self.tableWidgetServers)
        self.tabWidgetConfig.addTab(self.ServersTab, _fromUtf8(""))
        self.localTab = QtGui.QWidget()
        self.localTab.setObjectName(_fromUtf8("localTab"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.localTab)
        self.verticalLayout_3.setMargin(1)
        self.verticalLayout_3.setSpacing(1)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.splitter = QtGui.QSplitter(self.localTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setMinimumSize(QtCore.QSize(200, 0))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setOpaqueResize(False)
        self.splitter.setHandleWidth(1)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.tableWidgetLocaleCfgNode = QtGui.QTableWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidgetLocaleCfgNode.sizePolicy().hasHeightForWidth())
        self.tableWidgetLocaleCfgNode.setSizePolicy(sizePolicy)
        self.tableWidgetLocaleCfgNode.setMinimumSize(QtCore.QSize(200, 0))
        self.tableWidgetLocaleCfgNode.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tableWidgetLocaleCfgNode.setObjectName(_fromUtf8("tableWidgetLocaleCfgNode"))
        self.tableWidgetLocaleCfgNode.setColumnCount(1)
        self.tableWidgetLocaleCfgNode.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetLocaleCfgNode.setHorizontalHeaderItem(0, item)
        self.tableWidgetLocaleCfgArg = QtGui.QTableWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidgetLocaleCfgArg.sizePolicy().hasHeightForWidth())
        self.tableWidgetLocaleCfgArg.setSizePolicy(sizePolicy)
        self.tableWidgetLocaleCfgArg.setMinimumSize(QtCore.QSize(400, 0))
        self.tableWidgetLocaleCfgArg.setObjectName(_fromUtf8("tableWidgetLocaleCfgArg"))
        self.tableWidgetLocaleCfgArg.setColumnCount(2)
        self.tableWidgetLocaleCfgArg.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetLocaleCfgArg.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetLocaleCfgArg.setHorizontalHeaderItem(1, item)
        self.verticalLayout_3.addWidget(self.splitter)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton = QtGui.QPushButton(self.localTab)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.tabWidgetConfig.addTab(self.localTab, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidgetConfig)
        MainWindowTool.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindowTool)
        self.tabWidgetConfig.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindowTool)

    def retranslateUi(self, MainWindowTool):
        MainWindowTool.setWindowTitle(_translate("MainWindowTool", "MainWindow", None))
        item = self.tableWidgetServers.horizontalHeaderItem(0)
        item.setText(_translate("MainWindowTool", "服务类型", None))
        item = self.tableWidgetServers.horizontalHeaderItem(1)
        item.setText(_translate("MainWindowTool", "服务名称", None))
        item = self.tableWidgetServers.horizontalHeaderItem(2)
        item.setText(_translate("MainWindowTool", "程序路径", None))
        item = self.tableWidgetServers.horizontalHeaderItem(3)
        item.setText(_translate("MainWindowTool", "工作目录", None))
        item = self.tableWidgetServers.horizontalHeaderItem(4)
        item.setText(_translate("MainWindowTool", "环境变量", None))
        item = self.tableWidgetServers.horizontalHeaderItem(5)
        item.setText(_translate("MainWindowTool", "服务参数", None))
        item = self.tableWidgetServers.horizontalHeaderItem(6)
        item.setText(_translate("MainWindowTool", "启动后延时", None))
        item = self.tableWidgetServers.horizontalHeaderItem(7)
        item.setText(_translate("MainWindowTool", "启动", None))
        item = self.tableWidgetServers.horizontalHeaderItem(8)
        item.setText(_translate("MainWindowTool", "自动启动", None))
        item = self.tableWidgetServers.horizontalHeaderItem(9)
        item.setText(_translate("MainWindowTool", "不重复启动", None))
        self.tabWidgetConfig.setTabText(self.tabWidgetConfig.indexOf(self.ServersTab), _translate("MainWindowTool", "Servers", None))
        item = self.tableWidgetLocaleCfgNode.horizontalHeaderItem(0)
        item.setText(_translate("MainWindowTool", "配置节点名称", None))
        item = self.tableWidgetLocaleCfgArg.horizontalHeaderItem(0)
        item.setText(_translate("MainWindowTool", "参数名称", None))
        item = self.tableWidgetLocaleCfgArg.horizontalHeaderItem(1)
        item.setText(_translate("MainWindowTool", "参数值", None))
        self.pushButton.setText(_translate("MainWindowTool", "PushButton", None))
        self.tabWidgetConfig.setTabText(self.tabWidgetConfig.indexOf(self.localTab), _translate("MainWindowTool", "localcfg", None))

